# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57c2e1ae6e01e842b1489bfe8ef788c5ae2eedfb639d2a1ba3d0b248349a4109a0a5b2e0d6d23e26968b42210182b8e6462ec93a159ca87efa07fe9e4d2819e6

test:
  secret_key_base: 3b7ba152c97fdb74a9c3605d0aab2cf01a864bf6c9f793082ba520dc58ef845b53eb314ee2180b1fc6062b67f9f4cc77a9b96a156d036af9028a28e2d9d9ad27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
